// <auto-generated />
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(NotifyDbContext))]
    [Migration("20240223183051_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("DataAccess.DbNotificationEvent", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("VARCHAR")
                        .HasColumnName("session_id");

                    b.Property<string>("Card")
                        .IsRequired()
                        .HasColumnType("VARCHAR")
                        .HasColumnName("card");

                    b.Property<string>("EventDate")
                        .IsRequired()
                        .HasColumnType("VARCHAR")
                        .HasColumnName("event_date");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasColumnType("VARCHAR")
                        .HasColumnName("order_type");

                    b.Property<string>("WebsiteUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("website_url");

                    b.HasKey("SessionId");

                    b.ToTable("notify_event", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
